GET http://localhost:8080/notes HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/notes HTTP/1.1
content-type: application/json

{
    "content": "test"
}

###

DELETE http://localhost:8080/notes HTTP/1.1
content-type: application/json

{
    "id": "643022348552bfd2115d403e"
}

###

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "username": "User123",
    "password": "123password123"
}

###

PATCH http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "noteContent": "A new task",
    "username": "User123"
}

###

PATCH http://localhost:3000/users/deleteNote HTTP/1.1
content-type: application/json

{
    "noteId": "64284eac0c33b4d6ba30290b",
    "username": "User123"
}

###

GET http://localhost:3000/users/User123 HTTP/1.1
content-type: application/json
